### ISSUE TITLE
jython error

### ISSUE THREAD

**Issue by botiapa** [masteroftime/Python-Plugin-Loader#20]
Hello

If i start my craftbukkkit server (ver=1.10) i get some java errors and pythonloader won't load properly. So my script is not working at all.

Here is the full log:

`[23:40:31] [Server thread/INFO]: Starting minecraft server version 1.10
[23:40:31] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[23:40:31] [Server thread/INFO]: Loading properties
[23:40:31] [Server thread/INFO]: Default game type: SURVIVAL
[23:40:31] [Server thread/INFO]: Generating keypair
[23:40:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:40:32] [Server thread/INFO]: Using default channel type
[23:40:32] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-9856d8a (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[23:40:32] [Server thread/INFO]: [PythonLoader] Loading PythonLoader v0.4.1
[23:40:32] [Server thread/INFO]: [PythonLoader] File found: C:\Users\Boti/.jython
[23:40:32] [Server thread/INFO]: [PythonLoader] If your Python plugins behave oddly, please make sure this file contains "python.security.respectJavaAccessibility = false".
[23:40:32] [Server thread/ERROR]: org/python/core/PyObject initializing PythonLoader v0.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/python/core/PyObject
    at com.master.bukkit.python.PythonLoader.onLoad(PythonLoader.java:71) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:299) [cb.jar:git-Bukkit-9856d8a]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:256) [cb.jar:git-Bukkit-9856d8a]
    at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70) [cb.jar:git-Bukkit-9856d8a]
    at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14) [cb.jar:git-Bukkit-9856d8a]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183) [cb.jar:git-Bukkit-9856d8a]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:517) [cb.jar:git-Bukkit-9856d8a]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.python.core.PyObject
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[cb.jar:git-Bukkit-9856d8a]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[cb.jar:git-Bukkit-9856d8a]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    ... 8 more
[23:40:32] [Server thread/INFO]: Preparing level "world"
[23:40:33] [Server thread/INFO]: Preparing start region for level 0 (Seed: 1092924308036343563)
[23:40:34] [Server thread/INFO]: Preparing spawn area: 24%
[23:40:34] [Server thread/INFO]: Preparing start region for level 1 (Seed: 1092924308036343563)
[23:40:35] [Server thread/INFO]: Preparing spawn area: 84%
[23:40:36] [Server thread/INFO]: Preparing start region for level 2 (Seed: 1092924308036343563)
[23:40:36] [Server thread/INFO]: [PythonLoader] Enabling PythonLoader v0.4.1
[23:40:36] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:40:36] [Server thread/INFO]: Done (4,158s)! For help, type "help" or "?"
`

thanks for helping

**Comment by jomo** [comment]
Please try https://github.com/gdude2002/Python-Plugin-Loader, this project is dead.
